users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, validators, BooleanField
from wtforms.validators import Email, ValidationError, Regexp, Length, EqualTo, DataRequired
import re
from flask_wtf import RecaptchaField
import pyotp


    
def character_check(form, field):
    excluded_characters = "*?!'^+%&/()=}][{$#@<>"
    for char in field.data:
        if char in excluded_characters:
            raise ValidationError(f"Character {char} is not allowed in Name")


def password_check(form, field):
    p = re.compile(r'(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^A-Za-z0-9])')
    if not p.match(field.data):
        raise ValidationError(
            "Password must contain at least 1 special character, uppercase letter, lowercase letter and digit")


def postcode_check(form, field):
    p = re.compile("^[A-Z][0-9] [0-9][A-Z]{2}$")
    p2 = re.compile("^[A-Z][0-9]{2} [0-9][A-Z]{2}$")
    p3 = re.compile("^[A-Z]{2}[0-9] [0-9][A-Z]{2}$")
    if not p.match(field.data) and not p2.match(field.data) and not p3.match(field.data):
        raise ValidationError(
            "Postcode must be in the forms XY YXX, XYY YXX or XXY YXX where X is a letter and Y is a number. Letters "
            "must be all in caps.")


class RegisterForm(FlaskForm):
    email = StringField(validators=[Email(message="Please enter a valid e-mail address"),
                                    DataRequired(message="Field cannot be blank")])
    firstname = StringField(validators=[character_check, DataRequired(message="Field cannot be blank")])
    lastname = StringField(validators=[character_check, DataRequired(message="Field cannot be blank")])
    phone = StringField(
        validators=[Regexp(regex="^[0-9]{4}[-][0-9]{3}[-][0-9]{4}$", message="Phone number must be a String containing "
                                                                             "only digits (X) and dashes (-) of the "
                                                                             "form: XXXX-XXX-XXXX "), DataRequired(
            message="Field cannot be blank")])
    dob = StringField(
        validators=[Regexp(regex="^[0-3][0-9][/][0-1][0-2][/](19|20)[0-9]{2}$", message="Must be a String containing "
                                                                                        "only"
                                                                                        "appropriate digits and "
                                                                                        "forward slashes"
                                                                                        "(/) of the form: DD/MM/YYYY "
                                                                                        "- D (Day),"
                                                                                        "M (Month), Y (Year)."),
                    DataRequired(
                        message="Field cannot be blank")])
    postcode = StringField(validators=[postcode_check, DataRequired(message="Field cannot be blank")])
    password = PasswordField(
        validators=[Length(min=6, max=12, message="Password must be 6-12 characters long"), password_check,
                    DataRequired(message="Field cannot be blank")])
    confirm_password = PasswordField(validators=[EqualTo('password', message="Passwords do not match"),
                                                 DataRequired(message="Field cannot be blank")])
    submit = SubmitField()


class LoginForm(FlaskForm):
    email = StringField(validators=[Email(message="Please enter a valid e-mail address"),
                                    DataRequired(message="Field cannot be blank")])
    password = PasswordField(
        validators=[Length(min=6, max=12, message="Password must be 6-12 characters long"), password_check,
                    DataRequired(message="Field cannot be blank")])
    postcode = StringField(validators=[postcode_check, DataRequired(message="Field cannot be blank")])
    pin = StringField(
        validators=[
            DataRequired(message="Field cannot be blank")])
    recaptcha = RecaptchaField()
    submit = SubmitField()


class PasswordForm(FlaskForm):
    current_password = PasswordField(id='password', validators=[DataRequired()])
    show_password = BooleanField('Show password', id='check')
    new_password = PasswordField(
        validators=[Length(min=6, max=12, message="Password must be 6-12 characters long"), password_check,
                    DataRequired(message="Field cannot be blank")])
    confirm_new_password = PasswordField(
        validators=[DataRequired(), EqualTo('new_password', message='Both new password fields must be equal')])
    submit = SubmitField('Change Password')

users/views.py
# IMPORTS
import logging
from datetime import datetime

from flask import Blueprint, render_template, flash, redirect, url_for, session, request
from markupsafe import Markup

from app import db
from models import User
from users.forms import RegisterForm, LoginForm, PasswordForm
from flask_login import login_user, logout_user, login_required, current_user

# CONFIG
users_blueprint = Blueprint('users', __name__, template_folder='templates')


def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(error, 'error')


# VIEWS
# view registration
@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    # create signup form object
    form = RegisterForm()
    # if request method is POST or form is valid
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # if this returns a user, then the email already exists in database

        # if email already exists redirect user back to signup page with error message so user can try again
        if user:
            flash('Email address already exists', 'error')
            return render_template('users/register.html', form=form)

        # create a new user with the form data
        new_user = User(email=form.email.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        phone=form.phone.data,
                        password=form.password.data,
                        dob=form.dob.data,
                        postcode=form.postcode.data,
                        role='user')

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()

        logging.warning('SECURITY - User registration [%s, %s]', form.email.data, request.remote_addr)

        session["email"] = new_user.email
        session['authentication_attempts'] = 0
        # sends user to login page
        return redirect(url_for('users.setup_2fa'))
    else:
        flash_errors(form)

    # if request method is GET or form not valid re-render signup page
    return render_template('users/register.html', form=form)


# view user login
@users_blueprint.route('/login', methods=['GET', 'POST', ])
def login():
    if not session.get('authentication_attempts'):
        session['authentication_attempts'] = 0
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first();
        if not user or not user.verify_password(form.password.data) or not user.verify_pin(
                form.pin.data) or not user.verify_postcode(form.postcode.data):
            logging.warning('SECURITY - Invalid log in attempt [%s, %s]',
                            form.email.data,
                            request.remote_addr
                            )
            session['authentication_attempts'] += 1
            if session.get('authentication_attempts') >= 3:
                flash(Markup('Number of incorrect login attempts exceeded. Please click <a href = "/reset" > here < / '
                             'a > to reset.'))
                return render_template('users/login.html')
            flash('Email address, password or pin is incorrect. {} login attempts remaining'.format(
                3 - session.get('authentication_attempts')), 'error')
            return render_template('users/login.html', form=form)
        login_user(user)
        current_user.last_login = current_user.current_login
        current_user.current_login = datetime.now()
        session['authentication_attempts'] = 0
        db.session.commit()
        logging.warning('SECURITY - Log in [%s, %s, %s]',
                        current_user.id,
                        current_user.email,
                        request.remote_addr
                        )
        current_user.logins = current_user.logins + 1
        if current_user.role == "admin":
            return redirect(url_for('admin/admin'))

        else:
            return redirect(url_for('lottery.lottery'))
    else:
        flash_errors(form)
    # if request method is GET or form not valid re-render signup page
    return render_template('users/login.html', form=form)


@users_blueprint.route('/setup_2fa')
def setup_2fa():
    if 'email' not in session:
        return redirect(url_for('index'))
    user = User.query.filter_by(email=session['email']).first()
    if not user:
        return redirect(url_for('index'))
    del session['email']
    return render_template('users/setup_2fa.html', email=user.email, uri=user.get_2fa_uri())


@users_blueprint.route('/update_password', methods=['GET', 'POST'])
@login_required
def update_password():
    form = PasswordForm()

    if form.validate_on_submit():

        if not current_user or not current_user.verify_password(form.current_password.data):
            flash('Incorrect current password', 'error')
            return render_template('users/update_password.html', form=form)

        current_user.password = form.new_password.data
        db.session.commit()
        flash('Password changed successfully')

        return redirect(url_for('users.account'))

    return render_template('users/update_password.html', form=form)


# view user account
@users_blueprint.route('/account')
@login_required
def account():
    return render_template('users/account.html',
                           acc_no=current_user.id,
                           email=current_user.email,
                           firstname=current_user.firstname,
                           lastname=current_user.lastname,
                           phone=current_user.phone,
                           role=current_user.role,
                           dob=current_user.dob,
                           postcode=current_user.postcode)


@users_blueprint.route('/reset')
def reset():
    session['authentication_attempts'] = 0
    return redirect(url_for('users.login'))


@users_blueprint.route('/logout')
@login_required
def logout():
    logging.warning('SECURITY - Log out [%s, %s, %s]',
                    current_user.id,
                    current_user.email,
                    request.remote_addr
                    )
    logout_user()
    return redirect(url_for('index'))

templates/users/account.html
{% extends "base.html" %}

{% block content %}

    <div class="column is-6 is-offset-3">
        <h3 class="title">Your Account</h3>

        <div class="box">
            <table class="table">
            <tbody>
            {% with messages = get_flashed_messages() %}
                 {% if messages %}
                     <ul class=flashes>
                    {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
                <tr>
                    <th>Account No.</th>
                    <th>{{ acc_no }}</th>
                </tr>
                <tr>
                    <th>Email</th>
                    <th>{{ email }}</th>
                </tr>
                <tr>
                    <th>First Name</th>
                    <th>{{ firstname }}</th>
                </tr>
                <tr>
                    <th>Last Name</th>
                    <th>{{ lastname }}</th>
                </tr>
                <tr>
                    <th>Phone No.</th>
                    <th>{{ phone }}</th>
                </tr>
                <tr>
                    <th>Role</th>
                    <th>{{ role }}</th>
                </tr>
                <tr>
                    <th>Date Of Birth</th>
                    <th>{{ dob }}</th>
                </tr>
                <tr>
                    <th>Postcode</th>
                    <th>{{ postcode }}</th>
                </tr>
                <tr>
                    <th>Password</th>
                    <td><a style='color: blue' href="{{ url_for('users.update_password') }}">Change Password</a></td>
                </tr>
            </tbody>
            </table>
        </div>
    </div>


{% endblock %}

templates/users/login.html
{% extends "base.html" %}

{% if form %}
<form method="POST">
...
</form>
{% endif %}

{% block content %}
    <div class="column is-5 is-offset-4">
        <h3 class="title is-3">Login</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}. Go to <a href="{{ url_for('users.login') }}">login page</a>.
                    </div>
                {% endif %}
            {% endwith %}
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.email(class="input", placeholder="Email") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.password(class="input", placeholder="Password") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.postcode(class="input", placeholder="Postcode") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.pin(class="input", placeholder="Time-Based Pin") }}
                    </div>
                </div>
                <div>
                        {{ form.recaptcha }}
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/register.html
{% extends "base.html" %}

{% block content %}
    <div class="column is-5 is-offset-4">
        <h3 class="title is-3">Register</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}. Go to <a href="{{ url_for('users.login') }}">login page</a>.
                    </div>
                {% endif %}
            {% endwith %}
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.email(class="input", placeholder="Email") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.firstname(class="input", placeholder="First Name") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.lastname(class="input", placeholder="Last Name") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.phone(class="input", placeholder="Phone") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.dob(class="input", placeholder="Date of Birth (DD/MM/YYYY)") }}
                    </div>
                </div>
                  <div class="field">
                    <div class="control">
                        {{ form.postcode(class="input", placeholder="Postcode") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.password(class="input", placeholder="Password") }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                    </div>

                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/setup_2fa.html
{% extends "base.html" %}

{% block content %}

<h1 class="title">"2-Factor Authentication"</h1>

    <p>To set up 2-factor authentication under the account with email {{ email }},
    scan the following QR code with the Authy application on your Smartphone:</p>
    <p><img src="{{ qrcode(uri, box_size=5, border=5) }}" alt="QR Code"></p>
    <p>Once set up, please use your code on the <a href="{{ url_for('users.login') }}"><u>Login</u></a> page</p>
    <p>You will need to use this app to get a login code whenever you log in.</p>

{% endblock %}

templates/users/update_password.html
{% extends 'base.html' %}

{% block content %}
    <script type="text/javascript" src="{{ url_for('static', filename='listeners.js') }}"></script>
    <div class="column is-5 is-offset-4">
        <h3 class="title">Change Password</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.current_password(class="input", placeholder="Current Password") }}
                        {% for error in form.current_password.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.show_password() }}
                        {{ form.show_password.label }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.new_password(class="input", placeholder="New Password") }}
                        {% for error in form.new_password.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.confirm_new_password(class="input", placeholder="Confirm New Password") }}
                        {% for error in form.confirm_new_password.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}